language: scala
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
install: npm install -g newman
script:
- sbt test
- setsid nohup sbt run & && sleep 15
- newman run test/api_suite.json --ignore-redirects
