language: scala
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
install: npm install -g newman
script:
- sbt test
- sbt stage
- nohup ./target/universal/stage/bin/gcho-backend -Dconfig.file=conf/prod.conf &>/dev/null &
- sleep 30
- newman run test/api_suite.json --ignore-redirects
