swagger: 2.0
info:
  version: 0.3.4
  title: GCHO Backend
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
definitions:
  messages:
    type: array
    items:
      type: object
      required:
        - key
        - messages
      properties:
        key:
          type: string
        messages:
          type: array
          items:
            type: string
paths:
  /auth/signup:
    post:
      description: New user signup.
      parameters:
        - name: user data
          in: body
          required: true
          schema:
            type: object
            required:
              - name
              - email
              - password
            properties:
              name:
                type: string
              email:
                type: string
                format: email
              password:
                type: object
                required:
                  - password1
                  - password2
                properties:
                  password1:
                    type: string
                  password2:
                    type: string
      responses:
        202:
          description: Signup accepted and verification email sent.
        400:
          description: Signup data invalid.
          schema:
            $ref: '#/definitions/messages'
        409:
          description: User exists with this email as login.
  /auth/signup/{token}:
    get:
      description: Signup completion.
      parameters:
        - name: token
          in: path
          description: Email confirmation token.
          required: true
          type: string
      responses:
        200:
          description: Signup completed.
          headers:
            X-Auth-Token:
              description: User authentication token.
        404:
          description: No such token.
        410:
          description: Token expired.
  /auth/signin:
    post:
      description: Email/password sign-in.
      parameters:
        - name: credentials
          in: body
          description: User log in credentials.
          required: true
          schema:
            type: object
            required:
              - email
              - password
              - rememberMe
            properties:
              email:
                type: string
                format: email
              password:
                type: string
              rememberMe:
                type: boolean
      responses:
        202:
          description: User authenticated.
          headers:
            X-Auth-Token:
              description: User authentication token.
        400:
          description: Sign-in data invalid.
          schema:
            $ref: '#/definitions/messages'
        401:
          description: User email not confirmed.
        403:
          description: Password doesn't match.
        404:
          description: No user with this email.
  /auth/social/{provider}:
    get:
      description: Social authentication.
      parameters:
        - name: provider
          in: path
          description: Social authentication provider.
          required: true
          type: string
          enum:
            - google
            - facebook
        - name: code
          in: query
          description: OAuth2 authentication code.
          required: false
          type: string
      responses:
        200:
          description: OAuth2 code accepted.
          headers:
            X-Auth-Token:
              description: User authentication token.
        303:
          description: Redirect to social provider website for authentication.
        404:
          description: No such provider.
        409:
          description: Another user with same provider and email exists.
  /auth/signout:
    get:
      description: Discards authentication token.
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: User authentication token.
          type: string
      responses:
        200:
          description: User logged out.
        401:
          description: Authentication token invalid.
  /auth/reset:
    post:
      description: Password reset initiation.
      parameters:
        - name: email
          in: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
                format: email
      responses:
        202:
          description: Confirmation email was sent.
        400:
          description: Form data invalid.
          schema:
            $ref: '#/definitions/messages'
        404:
          description: No user with such email.
  /auth/reset/{token}:
    post:
      description: Password reset completion.
      parameters:
        - name: token
          in: path
          description: Email confirmation token.
          required: true
          type: string
        - name: password
          in: body
          required: true
          description: New password, repeated.
          schema:
            type: object
            required:
              - password1
              - password2
            properties:
              password1:
                type: string
              password2:
                type: string
      responses:
        202:
          description: Password changed.
        400:
          description: Form data invalid.
          schema:
            $ref: '#/definitions/messages'
        404:
          description: No such token.
        410:
          description: Token expired.
  /auth/change:
    post:
      description: Password change.
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: User authentication token.
          type: string
        - name: passwords
          in: body
          required: true
          schema:
            type: object
            required:
              - oldPassword
              - newPassword
            properties:
              oldPassword:
                type: string
              newPassword:
                type: string
      responses:
        202:
          description: Password updated.
        400:
          description: Form data invalid.
          schema:
            $ref: '#/definitions/messages'
        401:
          description: Authentication token invalid.
        403:
          description: Old password doesn't match.
